apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  namespace: "argocd"
  labels:
    app: api
    ephemeral: "true"
spec:
  project: "mission-dev"
  source:
    repoURL: "843238382912.dkr.ecr.us-west-2.amazonaws.com"
    chart: "mission-api-helm"
    targetRevision: "0.0.22"
    helm:
      valueFiles:
      - "values-dev.yaml"
  destination:
    server: "https://F40F64ECB7956B66F6DE3604BD41EA54.sk1.us-west-2.eks.amazonaws.com"
