apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - namespace: mission-api-cody
      - namespace: mission-api-bryan
      - namespace: mission-api-ellis
      - namespace: mission-api-metin
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: "mission-dev"
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/guestbook/{{cluster}}
      destination:
        server: "https://F40F64ECB7956B66F6DE3604BD41EA54.sk1.us-west-2.eks.amazonaws.com"
        namespace: {{namespace}}