apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.image-pull-policy: Never
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: api
    app: api
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: {{ .Values.api.deployment.containerPort }}
  selector:
    app: api
  type: LoadBalancer
  sessionAffinity: None
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4