#apiVersion: argoproj.io/v1alpha1
#kind: AppProject
#metadata:
#  annotations:
#    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
#    argocd.argoproj.io/sync-options: PruneLast=true
#    argocd.argoproj.io/sync-wave: "-2"
#  name: "mission-staging"
#  namespace: argocd
#spec:
#  clusterResourceWhitelist:
#  - group: '*'
#    kind: '*'
#  description: Staging cluster workloads
#  destinations:
#  - namespace: '*'
#    server: '*'
#  namespaceResourceWhitelist:
#  - group: '*'
#    kind: '*'
#  sourceRepos:
#  - '*'
#---