apiVersion: "argoproj.io/v1alpha1"
kind: "ApplicationSet"
metadata:
  name: "mission-api-dev"
spec:
  generators:
    - list:
        elements:
          - environment_name: dev-cody
            namespace: dev-cody-mission-api
            helm_tag: "0.0.20"
            api_image_tag: "0.0.15"
          - environment_name: dev-bryan
            namespace: dev-bryan-mission-api
            helm_tag: "0.0.20"
            api_image_tag: "0.0.15"
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: "mission-dev"
      source:
        repoURL: "843238382912.dkr.ecr.us-west-2.amazonaws.com"
        chart: "mission-api-helm"
        targetRevision: "{{helm_tag}}"
        helm:
          valuesFiles:
          - "values-dev.yaml"
          parameters:
            - name: "common.environment_name"
              value: '{{environment_name}}'
            - name: "common.namespace"
              value: '{{namespace}}'
            - name: "api.deployment.image.tag"
              value: '{{api_image_tag}}'
      destination:
        server: "https://F40F64ECB7956B66F6DE3604BD41EA54.sk1.us-west-2.eks.amazonaws.com"
        namespace: "{{namespace}}"
#      syncPolicy:
#        automated:
#          prune: true
#          selfHeal: true
#          allowEmpty: false
#        syncOptions:
#        - "PruneLast=true"
#        - "ApplyOutOfSyncOnly=true"
##        - "CreateNamespace=true"
##        managedNamespaceMetadata: # Sets the metadata for the application namespace. Only valid if CreateNamespace=true (see above), otherwise it's a no-op.
##          labels: # The labels to set on the application namespace
##            app: mission-api
##            elbv2.k8s.aws/pod-readiness-gate-inject: enabled
##          annotations: # The labels to set on the application namespace
##            app: mission-api
##            elbv2.k8s.aws/pod-readiness-gate-inject: enabled
