apiVersion: "argoproj.io/v1alpha1"
kind: "ApplicationSet"
metadata:
  name: "mission-api-prod"
spec:
  generators:
    - list:
        elements:
          - environment_name: "prod-us-west-1"
            namespace: "mission-api-prod-us-west-1"
            helm_tag: "0.0.22"
            api_image_tag: "0.0.15"
            cluster_url: "https://2D5AF68D64DDEEEC928AFCA8D89DED39.gr7.us-west-2.eks.amazonaws.com"
          - environment_name: "prod-us-west-2"
            namespace: "mission-api-prod-us-west-2"
            helm_tag: "0.0.22"
            api_image_tag: "0.0.15"
            cluster_url: "https://2D5AF68D64DDEEEC928AFCA8D89DED39.gr7.us-west-2.eks.amazonaws.com"
  template:
    metadata:
      name: 'mission-api-{{environment_name}}'
      labels:
        app: api
        helm_tag: "{{helm_tag}}"
        image_tag: "{{api_image_tag}}"
    spec:
      project: "mission-prod"
      source:
        repoURL: "843238382912.dkr.ecr.us-west-2.amazonaws.com"
        chart: "mission-api-helm"
        targetRevision: "{{helm_tag}}"
        helm:
          valueFiles:
            - "values-prod.yaml"
          parameters:
            - name: "common.environment_name"
              value: "{{environment_name}}"
            - name: "common.namespace"
              value: "{{namespace}}"
            - name: "api.deployment.image.tag"
              value: "{{api_image_tag}}"
      destination:
        server: "{{cluster_url}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - "PruneLast=true"
          - "ApplyOutOfSyncOnly=true"
