apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "mission-api-prod"
  namespace: "argocd"
  labels:
    app: api
spec:
  project: "mission-prod"
  source:
    repoURL: "843238382912.dkr.ecr.us-west-2.amazonaws.com"
    chart: "mission-api-helm"
    targetRevision: "0.0.22"
    helm:
      valueFiles: "values-prod.yaml"
      parameters:
        - name: "common.environment_name"
          value: 'mission-api'
        - name: "common.namespace"
          value: 'mission-api-prod'
        - name: "api.deployment.image.tag"
          value: "0.0.15"
  destination:
    server: "https://2D5AF68D64DDEEEC928AFCA8D89DED39.gr7.us-west-2.eks.amazonaws.com"
    namespace: "mission-api"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - "PruneLast=true"
    - "ApplyOutOfSyncOnly=true"
#        - "CreateNamespace=true"
#        managedNamespaceMetadata: # Sets the metadata for the application namespace. Only valid if CreateNamespace=true (see above), otherwise it's a no-op.
#          labels: # The labels to set on the application namespace
#            app: mission-api
#            elbv2.k8s.aws/pod-readiness-gate-inject: enabled
#          annotations: # The labels to set on the application namespace
#            app: mission-api
#            elbv2.k8s.aws/pod-readiness-gate-inject: enabled
