apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: {{ .Values.api.deployment.containerPort }}
  selector:
    app: api
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4