apiVersion: v1
kind: Service
metadata:
  name: db
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: db
spec:
  ports:
    - name: "{{ .Values.db.deployment.containerPort }}"
      port: {{ .Values.db.deployment.containerPort }}
      targetPort: {{ .Values.db.deployment.containerPort }}
  selector:
    io.kompose.service: db