{{/*apiVersion: external-secrets.io/v1beta1*/}}
{{/*kind: ExternalSecret*/}}
{{/*metadata:*/}}
{{/*  name: mission-api*/}}
{{/*  annotations:*/}}
{{/*    "helm.sh/hook": "pre-install"*/}}
{{/*    "helm.sh/hook-weight": "-5"*/}}
{{/*spec:*/}}
{{/*  dataFrom:*/}}
{{/*    - extract:*/}}
{{/*        conversionStrategy: Default*/}}
{{/*        decodingStrategy: None*/}}
{{/*        key: {{ .Values.common.external_secrets_key }}*/}}
{{/*  refreshInterval: 1m*/}}
{{/*  secretStoreRef:*/}}
{{/*    kind: ClusterSecretStore*/}}
{{/*    name: eso-aws-secrets-manager*/}}
{{/*  target:*/}}
{{/*    creationPolicy: Owner*/}}
{{/*    deletionPolicy: Retain*/}}
{{/*    name: mission-api*/}}
