common:
  secret_id: mission-api
  environment_name: example
  external_secrets_key: argocd-demo-dev/cluster-secrets/mission-api-01
  
# API
api:
  containerPort: 3000
  deployment:
    deploy: true
    replicas: 1
    containerPort: 6379
    env:
      node_env: dev01
      database_url: postgresql://fastapi:fastapi@db/fastapi
    image:
      name: 843238382912.dkr.ecr.us-west-2.amazonaws.com/mission-api
      tag: 0.0.3
  ingress:
    deploy: true

# Database
db:
  deployment:
    deploy: true
    replicas: 1
    containerPort: 5432
    env:
      databaseName: postgres
      hostname: db
      image:
        name: postgres
        tag: '14.5'
      type: postgresql
      username: admin
      password: admin

# Redis
redis:
  deployment:
    containerPort: 6379
    deploy: false
    replicas: 0
  image:
    name: redis
    tag: 7.0.5
  service:
    deploy: false
