apiVersion: "argoproj.io/v1alpha1"
kind: "ApplicationSet"
metadata:
  name: "mission-api-prod"
spec:
  generators:
    - list:
        elements:
          - cluster_url: https://2D5AF68D64DDEEEC928AFCA8D89DED39.gr7.us-west-2.eks.amazonaws.com
            environment_name: mission-api
            namespace: mission-api
            helm_tag: "0.0.22"
            api_image_tag: "0.0.15"
  template:
    metadata:
      name: '{{namespace}}'
    spec:
      project: "mission-prod"
      source:
#        enableOCI: "true"
        repoURL: "843238382912.dkr.ecr.us-west-2.amazonaws.com"
        chart: "mission-api-helm"
        targetRevision: "{{helm_tag}}"
        helm:
          valuesFile: "values-prod.yaml"
          parameters:
            - name: "common.environment_name"
              value: '{{environment_name}}'
            - name: "common.namespace"
              value: '{{namespace}}'
            - name: "api.deployment.image.tag"
              value: '{{api_image_tag}}'
      destination:
        server: "{{cluster_url}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - "PruneLast=true"
        - "ApplyOutOfSyncOnly=true"
#        - "CreateNamespace=true"
#        managedNamespaceMetadata: # Sets the metadata for the application namespace. Only valid if CreateNamespace=true (see above), otherwise it's a no-op.
#          labels: # The labels to set on the application namespace
#            app: mission-api
#            elbv2.k8s.aws/pod-readiness-gate-inject: enabled
#          annotations: # The labels to set on the application namespace
#            app: mission-api
#            elbv2.k8s.aws/pod-readiness-gate-inject: enabled
