apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    kubernetes.io/metadata.name: {{ .Values.namespace }}
  annotations:
    app: {{ .Values.app }}
